import { describe, it, expect } from 'vitest';
import { parsePostgresSQL } from '../../index';
import type { Table, Column } from '../../types';

describe('Edge Cases: Tables (PG12-19)', () => {
    describe('Temporary tables and CTAS', () => {
        it('should parse CREATE TABLE name TEMPORARY with ON COMMIT DELETE ROWS', () => {
            const sql = `CREATE TABLE session_cart TEMPORARY (session_id UUID, qty INT) ON COMMIT DELETE ROWS;`;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'session_cart');
            expect(table).toBeDefined();
            expect(table?.isTemporary).toBe(true);
            expect(table?.onCommit).toBe('DELETE_ROWS');
        });

        it('should parse CREATE TABLE AS SELECT (CTAS)', () => {
            const sql = `CREATE TABLE order_summary AS SELECT user_id, COUNT(*) AS cnt FROM orders GROUP BY user_id;`;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'order_summary');
            expect(table).toBeDefined();
            expect(table?.createAs).toBe(true);
            expect(table?.asQuery).toContain('SELECT');
        });
    });

    describe('[PG12] Generated columns', () => {
        it('should parse GENERATED ALWAYS AS ... STORED', () => {
            const sql = `
                CREATE TABLE products (
                    id SERIAL PRIMARY KEY,
                    price DECIMAL(10,2) NOT NULL,
                    quantity INTEGER NOT NULL,
                    total_price DECIMAL(12,2) GENERATED ALWAYS AS (price * quantity) STORED
                );
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'products');
            
            expect(table).toBeDefined();
            expect(table?.columns).toHaveLength(4);
            
            const generatedCol = table?.columns.find(c => c.name === 'total_price');
            expect(generatedCol).toBeDefined();
            expect(generatedCol?.isGenerated).toBe(true);
            expect(generatedCol?.generatedExpression).toBe('price * quantity');
            expect(generatedCol?.generatedType).toBe('STORED');
            expect(generatedCol?.type).toBe('DECIMAL(12,2)');
        });
    });

    describe('[PG18] VIRTUAL generated columns', () => {
        it('should parse GENERATED ALWAYS AS ... VIRTUAL', () => {
            const sql = `
                CREATE TABLE orders (
                    id SERIAL PRIMARY KEY,
                    status TEXT,
                    computed_status TEXT GENERATED ALWAYS AS (UPPER(status)) VIRTUAL
                );
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'orders');
            
            const generatedCol = table?.columns.find(c => c.name === 'computed_status');
            expect(generatedCol).toBeDefined();
            expect(generatedCol?.isGenerated).toBe(true);
            expect(generatedCol?.generatedType).toBe('VIRTUAL');
        });
    });

    describe('[PG12] Identity columns', () => {
        it('should parse GENERATED ALWAYS AS IDENTITY with full sequence options', () => {
            const sql = `
                CREATE TABLE sessions (
                    id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1000 INCREMENT BY 5 MINVALUE 1000 MAXVALUE 999999 NO CYCLE CACHE 10),
                    user_id UUID NOT NULL
                );
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'sessions');
            
            expect(table).toBeDefined();
            const idCol = table?.columns.find(c => c.name === 'id');
            expect(idCol).toBeDefined();
            expect(idCol?.type).toBe('BIGINT');
            expect(idCol?.defaultValue).toContain('IDENTITY');
        });

        it('should parse GENERATED BY DEFAULT AS IDENTITY', () => {
            const sql = `
                CREATE TABLE items (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                    name TEXT
                );
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'items');
            
            const idCol = table?.columns.find(c => c.name === 'id');
            expect(idCol).toBeDefined();
            expect(idCol?.defaultValue).toContain('IDENTITY');
        });
    });

    describe('Multi-column constraints with advanced options', () => {
        it('should parse DEFERRABLE INITIALLY DEFERRED constraints', () => {
            const sql = `
                CREATE TABLE accounts (
                    id SERIAL PRIMARY KEY,
                    parent_id INTEGER,
                    CONSTRAINT fk_parent FOREIGN KEY (parent_id) REFERENCES accounts(id)
                        DEFERRABLE INITIALLY DEFERRED
                );
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'accounts');
            
            expect(table?.foreignKeys).toHaveLength(1);
            expect(table?.foreignKeys[0].deferrable).toBe(true);
            expect(table?.foreignKeys[0].initiallyDeferred).toBe(true);
        });

        it('should parse NOT VALID constraint', () => {
            const sql = `
                CREATE TABLE data (
                    id SERIAL PRIMARY KEY,
                    email TEXT,
                    CONSTRAINT valid_email CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$') NOT VALID
                );
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'data');
            
            expect(table?.checkConstraints).toHaveLength(1);
            expect(table?.checkConstraints[0].notValid).toBe(true);
        });
    });

    describe('[PG12] EXCLUDE constraints', () => {
        it('should parse EXCLUDE USING gist with && operator', () => {
            const sql = `
                CREATE TABLE reservations (
                    id SERIAL PRIMARY KEY,
                    room_id INTEGER NOT NULL,
                    during TSRANGE,
                    EXCLUDE USING gist (room_id WITH =, during WITH &&)
                );
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'reservations');
            
            expect(table?.constraints).toBeDefined();
        });
    });

    describe('[PG18] EXCLUDE ... WITHOUT OVERLAPS', () => {
        it('should parse WITHOUT OVERLAPS temporal constraint', () => {
            const sql = `
                CREATE TABLE employee_assignments (
                    employee_id INTEGER,
                    project_id INTEGER,
                    valid_from DATE,
                    valid_to DATE,
                    CONSTRAINT no_overlap EXCLUDE USING gist (
                        employee_id WITH =,
                        PERIOD valid_from, valid_to WITHOUT OVERLAPS
                    )
                );
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'employee_assignments');
            
            expect(table?.withoutOverlaps).toBe(true);
        });
    });

    describe('DEFAULT values with function calls', () => {
        it('should parse DEFAULT nextval with regclass cast', () => {
            const sql = `
                CREATE TABLE events (
                    id INTEGER DEFAULT nextval('events_id_seq'::regclass),
                    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
                );
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'events');
            
            const idCol = table?.columns.find(c => c.name === 'id');
            expect(idCol?.defaultValue).toContain('nextval');
            
            const createdCol = table?.columns.find(c => c.name === 'created_at');
            expect(createdCol?.defaultValue).toContain('CURRENT_TIMESTAMP');
        });
    });

    describe('LIKE clause', () => {
        it('should parse LIKE table with INCLUDING options', () => {
            const sql = `
                CREATE TABLE orders_archive (LIKE orders INCLUDING DEFAULTS EXCLUDING CONSTRAINTS INCLUDING INDEXES);
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'orders_archive');
            
            expect(table).toBeDefined();
            expect(table?.likeTable).toBe('orders');
        });
    });

    describe('Table inheritance', () => {
        it('should parse INHERITS (parent_table)', () => {
            const sql = `
                CREATE TABLE cities (
                    name TEXT,
                    population REAL
                );
                CREATE TABLE capitals (
                    state TEXT
                ) INHERITS (cities);
            `;
            const result = parsePostgresSQL(sql);
            const capitalsTable = result.tables.find(t => t.name === 'capitals');
            
            expect(capitalsTable).toBeDefined();
            expect(capitalsTable?.inherits).toContain('cities');
            expect(capitalsTable?.inheritsFrom).toBe('cities');
        });
    });

    describe('[PG12] Partitioning', () => {
        it('should parse PARTITION BY RANGE', () => {
            const sql = `
                CREATE TABLE measurements (
                    id SERIAL,
                    created_at TIMESTAMPTZ NOT NULL,
                    value NUMERIC
                ) PARTITION BY RANGE (created_at);
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'measurements');
            
            expect(table?.isPartitioned).toBe(true);
            expect(table?.partitionType).toBe('range');
            expect(table?.partitionKey).toContain('created_at');
        });

        it('should parse PARTITION BY LIST', () => {
            const sql = `
                CREATE TABLE sales (
                    id SERIAL,
                    region TEXT NOT NULL,
                    amount NUMERIC
                ) PARTITION BY LIST (region);
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'sales');
            
            expect(table?.partitionType).toBe('list');
        });

        it('should parse PARTITION BY HASH', () => {
            const sql = `
                CREATE TABLE users (
                    id BIGINT,
                    data JSONB
                ) PARTITION BY HASH (id);
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'users');
            
            expect(table?.partitionType).toBe('hash');
        });
    });

    describe('Storage parameters', () => {
        it('should parse WITH (storage parameters)', () => {
            const sql = `
                CREATE TABLE logs (
                    id SERIAL PRIMARY KEY,
                    message TEXT
                ) WITH (fillfactor=80, parallel_workers=4, autovacuum_enabled=false, toast.autovacuum_enabled=true);
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'logs');
            
            expect(table?.['with']).toBeDefined();
            expect(table?.['with']?.fillfactor).toBe(80);
        });
    });

    describe('Row Level Security', () => {
        it('should parse ENABLE ROW LEVEL SECURITY', () => {
            const sql = `
                CREATE TABLE sensitive_data (
                    id SERIAL PRIMARY KEY,
                    data TEXT
                );
                ALTER TABLE sensitive_data ENABLE ROW LEVEL SECURITY;
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'sensitive_data');
            
            expect(table?.rlsEnabled).toBe(true);
        });
    });

    describe('[PG18] PERIOD SYSTEM_TIME', () => {
        it('should parse PERIOD for temporal tables', () => {
            const sql = `
                CREATE TABLE employees (
                    id SERIAL PRIMARY KEY,
                    name TEXT NOT NULL,
                    valid_from TIMESTAMPTZ GENERATED ALWAYS AS ROW START,
                    valid_to TIMESTAMPTZ GENERATED ALWAYS AS ROW END,
                    PERIOD SYSTEM_TIME (valid_from, valid_to)
                ) WITH SYSTEM VERSIONING;
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'employees');
            
            expect(table?.period).toBeDefined();
            expect(table?.period?.name).toBe('SYSTEM_TIME');
            expect(table?.period?.startColumn).toBe('valid_from');
            expect(table?.period?.endColumn).toBe('valid_to');
            expect(table?.withSystemVersioning).toBe(true);
        });
    });

    describe('[PG18] NOT ENFORCED constraint', () => {
        it('should parse CHECK constraint with NOT ENFORCED', () => {
            const sql = `
                CREATE TABLE future_events (
                    id SERIAL PRIMARY KEY,
                    event_date DATE,
                    CONSTRAINT chk_future CHECK (event_date > CURRENT_DATE) NOT ENFORCED
                );
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'future_events');
            
            expect(table?.checkConstraints).toHaveLength(1);
            expect(table?.checkConstraints[0].enforced).toBe(false);
        });
    });

    describe('[PG16] REGROLE/REGNAMESPACE defaults', () => {
        it('should parse DEFAULT with regrole cast', () => {
            const sql = `
                CREATE TABLE audit_log (
                    id SERIAL PRIMARY KEY,
                    created_by REGROLE DEFAULT current_role::regrole,
                    schema_name REGNAMESPACE DEFAULT current_schema::regnamespace
                );
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'audit_log');
            
            const createdBy = table?.columns.find(c => c.name === 'created_by');
            expect(createdBy?.type).toBe('REGROLE');
            expect(createdBy?.defaultValue).toContain('current_role');
        });
    });

    describe('Multiple collations', () => {
        it('should parse column-level COLLATE', () => {
            const sql = `
                CREATE TABLE multilingual (
                    id SERIAL PRIMARY KEY,
                    name_en TEXT COLLATE "en_US",
                    name_jp TEXT COLLATE "C"
                );
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'multilingual');
            
            const enCol = table?.columns.find(c => c.name === 'name_en');
            expect(enCol?.type).toContain('TEXT');
        });
    });

    describe('Complex foreign keys', () => {
        it('should parse multi-column foreign key', () => {
            const sql = `
                CREATE TABLE order_details (
                    order_id INTEGER,
                    product_id INTEGER,
                    quantity INTEGER,
                    PRIMARY KEY (order_id, product_id),
                    FOREIGN KEY (order_id, product_id) REFERENCES orders(order_id, product_id)
                        ON DELETE CASCADE ON UPDATE RESTRICT
                );
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'order_details');
            
            expect(table?.primaryKey).toBeDefined();
            expect(table?.primaryKey?.columns).toHaveLength(2);
            expect(table?.foreignKeys).toHaveLength(1);
            expect(table?.foreignKeys[0].onDelete).toBe('CASCADE');
        });
    });

    describe('SERIAL vs explicit sequence', () => {
        it('should parse SERIAL as auto-sequence', () => {
            const sql = `
                CREATE TABLE items (
                    id SERIAL PRIMARY KEY,
                    custom_id INTEGER DEFAULT nextval('custom_seq'::regclass)
                );
            `;
            const result = parsePostgresSQL(sql);
            const table = result.tables.find(t => t.name === 'items');
            
            expect(table).toBeDefined();
            expect(table?.columns).toHaveLength(2);
        });
    });
});
