-- PG13-specific DDL

CREATE TABLE stats_tbl (a INT, b INT, c TEXT);

CREATE STATISTICS s_ndistinct (ndistinct) ON a, b FROM stats_tbl;
CREATE STATISTICS s_deps (dependencies) ON a, b FROM stats_tbl;
CREATE STATISTICS s_mcv (mcv) ON a, b FROM stats_tbl;
CREATE STATISTICS s_combo (ndistinct, dependencies) ON a, b FROM stats_tbl;
CREATE STATISTICS s_all (ndistinct, dependencies, mcv) ON a, b, c FROM stats_tbl;
CREATE STATISTICS s_expr ON a, lower(c) FROM stats_tbl;

CREATE TABLE part_trg (id INT, dt DATE) PARTITION BY RANGE (dt);
CREATE TABLE part_trg_2024 PARTITION OF part_trg FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');
CREATE TRIGGER trg_part AFTER INSERT ON part_trg FOR EACH ROW EXECUTE FUNCTION fn_sql();

CREATE INDEX brin_idx ON stats_tbl USING brin (a) WITH (pages_per_range = 128, autosummarize = on);

DROP DATABASE IF EXISTS old_db WITH (FORCE);
REINDEX INDEX CONCURRENTLY idx_include_single;

CREATE STATISTICS s_pad_21 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_22 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_23 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_24 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_25 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_26 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_27 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_28 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_29 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_30 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_31 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_32 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_33 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_34 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_35 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_36 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_37 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_38 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_39 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_40 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_41 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_42 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_43 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_44 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_45 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_46 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_47 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_48 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_49 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_50 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_51 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_52 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_53 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_54 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_55 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_56 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_57 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_58 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_59 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_60 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_61 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_62 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_63 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_64 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_65 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_66 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_67 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_68 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_69 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_70 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_71 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_72 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_73 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_74 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_75 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_76 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_77 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_78 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_79 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_80 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_81 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_82 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_83 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_84 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_85 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_86 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_87 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_88 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_89 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_90 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_91 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_92 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_93 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_94 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_95 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_96 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_97 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_98 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_99 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_100 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_101 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_102 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_103 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_104 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_105 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_106 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_107 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_108 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_109 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_110 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_111 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_112 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_113 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_114 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_115 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_116 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_117 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_118 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_119 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_120 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_121 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_122 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_123 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_124 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_125 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_126 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_127 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_128 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_129 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_130 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_131 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_132 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_133 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_134 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_135 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_136 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_137 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_138 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_139 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_140 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_141 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_142 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_143 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_144 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_145 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_146 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_147 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_148 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_149 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_150 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_151 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_152 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_153 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_154 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_155 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_156 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_157 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_158 (ndistinct) ON a FROM stats_tbl;
CREATE STATISTICS s_pad_159 (ndistinct) ON a FROM stats_tbl;
