-- PG16-specific DDL

CREATE TABLE reg_tbl (
  id SERIAL PRIMARY KEY,
  created_by regrole DEFAULT current_user::regrole,
  ns regnamespace DEFAULT 'public'::regnamespace
);

CREATE TYPE comp16 AS (a INT, b TEXT);
ALTER TYPE comp16 RENAME ATTRIBUTE b TO beta;

CREATE DATABASE locale_db WITH LOCALE_PROVIDER = icu ICU_LOCALE = 'en-US';

ALTER TABLE reg_tbl SET (access_method = heap);

CREATE PUBLICATION pub16 FOR TABLE reg_tbl;
CREATE SUBSCRIPTION sub16 CONNECTION 'host=localhost dbname=test' PUBLICATION pub16;

ALTER TABLE reg_tbl ADD COLUMN col_19 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_20 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_21 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_22 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_23 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_24 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_25 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_26 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_27 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_28 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_29 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_30 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_31 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_32 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_33 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_34 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_35 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_36 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_37 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_38 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_39 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_40 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_41 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_42 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_43 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_44 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_45 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_46 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_47 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_48 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_49 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_50 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_51 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_52 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_53 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_54 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_55 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_56 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_57 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_58 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_59 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_60 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_61 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_62 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_63 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_64 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_65 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_66 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_67 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_68 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_69 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_70 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_71 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_72 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_73 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_74 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_75 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_76 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_77 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_78 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_79 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_80 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_81 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_82 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_83 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_84 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_85 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_86 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_87 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_88 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_89 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_90 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_91 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_92 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_93 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_94 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_95 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_96 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_97 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_98 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_99 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_100 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_101 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_102 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_103 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_104 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_105 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_106 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_107 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_108 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_109 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_110 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_111 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_112 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_113 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_114 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_115 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_116 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_117 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_118 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_119 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_120 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_121 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_122 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_123 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_124 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_125 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_126 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_127 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_128 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_129 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_130 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_131 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_132 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_133 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_134 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_135 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_136 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_137 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_138 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_139 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_140 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_141 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_142 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_143 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_144 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_145 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_146 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_147 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_148 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_149 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_150 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_151 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_152 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_153 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_154 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_155 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_156 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_157 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_158 regrole DEFAULT current_user::regrole;
ALTER TABLE reg_tbl ADD COLUMN col_159 regrole DEFAULT current_user::regrole;
